package autominion.database.persistence.entities;
// default package
// Generated 2 feb 2023 9:48:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "customers", catalog = "autominionbbdd")
public class Customers extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;
	private String surname1;
	private String surname2;
	private String phone;
	private String email;
	private String profileImage;
	private String address;
	private Set<Vehicles> vehicleses = new HashSet<Vehicles>(0);
	private Set<Salesproposal> salesproposals = new HashSet<Salesproposal>(0);
	private Set<Repairs> repairses = new HashSet<Repairs>(0);

	public Customers() {
	}

	public Customers(String name, String surname1, String surname2, String phone, String email,
			String profileImage, String address, Set<Vehicles> vehicleses, Set<Salesproposal> salesproposals,
			Set<Repairs> repairses) {
		this.name = name;
		this.surname1 = surname1;
		this.surname2 = surname2;
		this.phone = phone;
		this.email = email;
		this.profileImage = profileImage;
		this.address = address;
		this.vehicleses = vehicleses;
		this.salesproposals = salesproposals;
		this.repairses = repairses;
	}
	
	public Customers(String name, String surname1, String surname2, String phone, String email, String address) {
		this.name = name;
		this.surname1 = surname1;
		this.surname2 = surname2;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.profileImage = null;
		this.vehicleses = null;
		this.salesproposals = null;
		this.repairses = null;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname1", length = 20)
	public String getSurname1() {
		return this.surname1;
	}

	public void setSurname1(String surname1) {
		this.surname1 = surname1;
	}

	@Column(name = "surname2", length = 20)
	public String getSurname2() {
		return this.surname2;
	}

	public void setSurname2(String surname2) {
		this.surname2 = surname2;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "profileImage", length = 65535)
	public String getProfileImage() {
		return this.profileImage;
	}

	public void setProfileImage(String profileImage) {
		this.profileImage = profileImage;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
	public Set<Vehicles> getVehicleses() {
		return this.vehicleses;
	}

	public void setVehicleses(Set<Vehicles> vehicleses) {
		this.vehicleses = vehicleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
	public Set<Salesproposal> getSalesproposals() {
		return this.salesproposals;
	}

	public void setSalesproposals(Set<Salesproposal> salesproposals) {
		this.salesproposals = salesproposals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
	public Set<Repairs> getRepairses() {
		return this.repairses;
	}

	public void setRepairses(Set<Repairs> repairses) {
		this.repairses = repairses;
	}

}
