package autominion.database.persistence.entities;
// default package
// Generated 2 feb 2023 9:48:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Salesemployees generated by hbm2java
 */
@Entity
@Table(name = "salesemployees", catalog = "autominionbbdd")
public class Salesemployees extends AbstractEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long id;
	private Employees employees;
	private Set<Salesproposal> salesproposals = new HashSet<Salesproposal>(0);

	public Salesemployees() {
	}

	public Salesemployees(Employees employees) {
		this.employees = employees;
	}

	public Salesemployees(Employees employees, Set<Salesproposal> salesproposals) {
		this.employees = employees;
		this.salesproposals = salesproposals;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "employees"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesemployees")
	public Set<Salesproposal> getSalesproposals() {
		return this.salesproposals;
	}

	public void setSalesproposals(Set<Salesproposal> salesproposals) {
		this.salesproposals = salesproposals;
	}

}
