package autominion.database.persistence.entities;
// default package
// Generated 2 feb 2023 9:48:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Speciality generated by hbm2java
 */
@Entity
@Table(name = "speciality", catalog = "autominionbbdd", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Speciality implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long id;
	private String name;
	private Set<Mechanics> mechanicses = new HashSet<Mechanics>(0);

	public Speciality() {
	}

	public Speciality(String name, Set<Mechanics> mechanicses) {
		this.name = name;
		this.mechanicses = mechanicses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "mechanicspeciality", catalog = "autominionbbdd", joinColumns = {
			@JoinColumn(name = "SpecialityId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "MechanicId", nullable = false, updatable = false) })
	public Set<Mechanics> getMechanicses() {
		return this.mechanicses;
	}

	public void setMechanicses(Set<Mechanics> mechanicses) {
		this.mechanicses = mechanicses;
	}

}
